"""empty message

Revision ID: 04fd16b7f599
Revises: 46aa7d0821c3
Create Date: 2023-01-26 21:12:28.231357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fd16b7f599'
down_revision = '46aa7d0821c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_date', sa.String(length=10), nullable=True))
        batch_op.drop_column('entry_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('storage_date')

    # ### end Alembic commands ###
