"""empty message

Revision ID: 0e8a985ca667
Revises: 
Create Date: 2023-01-26 12:55:12.896547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8a985ca667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('entry_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('entry_date', sa.String(length=10), nullable=True),
    sa.Column('expiration_date', sa.String(length=10), nullable=True),
    sa.Column('inserted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inserted_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('employees')
    # ### end Alembic commands ###
