"""empty message

Revision ID: 46aa7d0821c3
Revises: 6b7e2ae8a07c
Create Date: 2023-01-26 21:00:55.829077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aa7d0821c3'
down_revision = '6b7e2ae8a07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True, load_only=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
