"""empty message

Revision ID: 56694d74c85f
Revises: 54bb95cfe239
Create Date: 2023-01-25 15:54:51.200180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56694d74c85f'
down_revision = '54bb95cfe239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employees', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employees', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
