"""empty message

Revision ID: 723e0138d4ca
Revises: 803ad6c4ba0c
Create Date: 2023-01-25 14:52:13.472741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723e0138d4ca'
down_revision = '803ad6c4ba0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('entry_date', sa.String(length=10), nullable=True),
    sa.Column('expiration_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products')
    # ### end Alembic commands ###
