"""empty message

Revision ID: 889c4c0a76d1
Revises: e01ffb2d5ead
Create Date: 2023-01-26 21:20:34.320707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889c4c0a76d1'
down_revision = 'e01ffb2d5ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=25), nullable=True),
    sa.Column('entry_date', sa.String(length=10), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
