"""empty message

Revision ID: 905d0fec15ae
Revises: 0e8a985ca667
Create Date: 2023-01-26 14:17:58.456691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905d0fec15ae'
down_revision = '0e8a985ca667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
