"""empty message

Revision ID: e716e30fbd73
Revises: d3b5c460a983
Create Date: 2023-01-25 14:32:01.978586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e716e30fbd73'
down_revision = 'd3b5c460a983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employees', schema=None) as batch_op:
        batch_op.alter_column('entry_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.DateTime(timezone=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Employees', schema=None) as batch_op:
        batch_op.alter_column('entry_date',
               existing_type=sa.DateTime(timezone=10),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
